### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by heldopslippers** [factore/tenon#1]
Tried to get this working on rails 4.1.6 
Which rails version is supported? 
using ruby 2.1.2

**Comment by SeanRoberts** [comment]
This should work with Rails 4.1 and Ruby 2.1 but we haven't been able to test in every environment.  What kind of issues are you running into?

**Comment by heldopslippers** [comment]
Hmm weird, The rake tasks are not running.

**Comment by SeanRoberts** [comment]
Can you add the backtraces and some more info about your environment?

**Comment by adriand** [comment]
This may also be helpful:

https://gist.github.com/adriand/bffe383f9311069811f0

**Comment by heldopslippers** [comment]
aah awesome. I will have a look. It's probably something in my environment. Will give it a try tomorrow.
